stateDiagram-v2
    [*] --> Publicado

    state "Concurso publicado" as Publicado
    state "Submissões ainda não abertas" as NaoAberto
    state "Submissões abertas" as Aberto
    state "Proposta em preparação" as Preparacao
    state "Proposta submetida no AcinGov" as Submetida
    state "Prazo de submissão encerrado" as Fechado
    state "A aguardar resultado" as AguardarResultado
    state "Concurso ganho" as Ganho
    state "Concurso não ganho" as Perdido
    state "Não participou" as NaoParticipou

    Publicado --> NaoAberto

    NaoAberto --> Aberto: Abre o prazo de submissão

    Aberto --> Preparacao: Empresa decide concorrer
    Aberto --> NaoParticipou: Empresa decide não concorrer

    Preparacao --> Submetida: Submete proposta\nno AcinGov

    Preparacao --> Fechado: Prazo termina\nsem submissão

    Submetida --> Fechado: Termina o prazo\nde submissão

    Fechado --> AguardarResultado: Propostas são avaliadas

    AguardarResultado --> Ganho: Adjudicação à empresa
    AguardarResultado --> Perdido: Adjudicação a outra empresa

    Ganho --> [*]
    Perdido --> [*]
    NaoParticipou --> [*]