#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
WRITTEN_ENV=()    # keys written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)
ENV_TMP=""

cleanup_env_tmp() {
  local exit_status=$?
  trap - EXIT
  if [[ -n "$ENV_TMP" ]]; then
    rm -f -- "$ENV_TMP" || true
    ENV_TMP=""
  fi
  exit "$exit_status"
}
trap cleanup_env_tmp EXIT

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then
    value="${value:1:${#value}-2}"
    value="${value//"$sq"/\'}"
  fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM${e}[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if ((rc)) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if ((rc)) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600 and rejects unsafe targets.
write_env() {
  local key="$1" value="$2" grep_status sq="'\\''"
  if [[ -L "$ENV_FILE" || (-e "$ENV_FILE" && ! -f "$ENV_FILE") ]]; then
    warn "Refusing to write to a symlink or non-regular file: $ENV_FILE"
    return 1
  fi
  [[ -e "$ENV_FILE" ]] || (umask 077 && : >"$ENV_FILE")
  chmod 600 "$ENV_FILE"
  ENV_TMP=$(mktemp "$PROJECT_ROOT/.env.XXXXXX")
  chmod 600 "$ENV_TMP"
  if grep -vE "^${key}=" "$ENV_FILE" >"$ENV_TMP"; then
    :
  else
    grep_status=$?
    if ((grep_status != 1)); then
      warn "Could not read $ENV_FILE; existing contents were not changed"
      return 1
    fi
  fi
  if ! printf "%s='%s'\n" "$key" "${value//\'/$sq}" >>"$ENV_TMP"; then
    warn "Could not prepare the updated $ENV_FILE; existing contents were not changed"
    return 1
  fi
  if ! mv -f -- "$ENV_TMP" "$ENV_FILE"; then
    warn "Could not replace $ENV_FILE; existing contents were not changed"
    return 1
  fi
  ENV_TMP=""
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
ENV_FILE="$PROJECT_ROOT/.env"

validate_env_target() {
  if [[ -L "$ENV_FILE" || (-e "$ENV_FILE" && ! -f "$ENV_FILE") ]]; then
    warn "Refusing to use a symlink or non-regular file: $ENV_FILE"
    return 1
  fi
  if [[ -f "$ENV_FILE" ]] && ! chmod 600 "$ENV_FILE"; then
    warn "Could not restrict permissions on $ENV_FILE"
    return 1
  fi
}

if ! validate_env_target; then exit 1; fi

TOTAL_STAGES=3

banner "Discord MCP setup"

stage "Check bot access"
open_url "https://discord.com/developers/applications"
say "Select the existing application for this bot, or create one if needed."
say "The bot needs View Channel permission in the target channels."
if ! confirm "Is this bot already installed in the target server and able to view the channels?"; then
  step "From the application's General Information page, copy its Application ID."
  ask APP_ID "Application ID (public; used only to build the invite link):"
  if [[ ! "$APP_ID" =~ ^[0-9]{17,20}$ ]]; then
    warn "That does not look like a Discord Application ID. Re-run the wizard and try again."
    exit 1
  fi

  # Discord's documented bot authorization flow uses scope=bot and a permission bitset.
  invite_url="https://discord.com/oauth2/authorize?client_id=${APP_ID}&scope=bot&permissions=1024"
  note "This requests only View Channel (permission bit 1024), not message history or write/moderation permissions."
  if confirm "Open Discord's authorization page to add this bot to a server?"; then
    open_url "$invite_url"
    step "Choose the target server and authorize the bot. You need permission to add apps to that server."
    pause "After Discord confirms the installation, press Enter"
  else
    SKIPPED+=("Discord bot installation; a server owner/admin must install it before the read tests")
    warn "Skipped bot installation."
  fi
fi

stage "Save the official bot token"
open_url "https://discord.com/developers/applications"
say "Open the same application, then select Bot in its settings."
if confirm "Do you already have a valid current bot token ready to paste?"; then
  step "Use that existing bot token; do not reset it."
else
  warn "Resetting the token invalidates the old token anywhere else it is used."
  if confirm "Do you authorize resetting this bot token now?"; then
    step "On the Bot page, use Reset Token under Build-a-Bot; complete any Discord confirmation, then copy the new token immediately."
    pause "After copying the token, press Enter"
  else
    SKIPPED+=("Discord bot token was not captured; no token reset was performed")
    warn "Stopped before token reset. No credential was saved."
    finish
    exit 0
  fi
fi
if ! ask_secret DISCORD_TOKEN "Paste the Discord bot token (input is hidden):"; then
  SKIPPED+=("Discord bot token was not captured")
  warn "No token was entered."
  finish
  exit 0
fi
if [[ -z "$DISCORD_TOKEN" ]]; then
  SKIPPED+=("Discord bot token was not captured")
  warn "The token was empty; no credential was saved."
  finish
  exit 0
fi
write_env DISCORD_TOKEN "$DISCORD_TOKEN"
chmod 600 "$ENV_FILE"
export DISCORD_TOKEN
unset APP_ID

stage "Verify Pi MCP and run read-only checks"
step "Checking Pi's native MCP connection and discovering the Discord tools."
if pi mcp list; then
  note "Pi connected to its enabled MCP servers and listed their available tools."
else
  SKIPPED+=("Pi MCP connection/tool discovery did not pass; review the error above")
  warn "The MCP check failed. The interactive read-only check may also fail until this is fixed."
fi
step "Starting Pi with DISCORD_TOKEN in its environment."
say "In Pi, use only mcp__discord__list_servers, then mcp__discord__get_channels for one server returned by the first call."
say "Return server and channel names only. Do not read messages or call any send, edit, create, delete, moderation, role, reaction, or permission-changing tool."
say "For future Pi sessions, load this project's .env before starting Pi: set -a; source .env; set +a; pi"
pause "Press Enter to open Pi for the read-only server/channel check"
if pi; then
  :
else
  warn "Pi exited with an error; review its output before retrying."
fi
unset DISCORD_TOKEN

finish
