#!/usr/bin/env bash
# shellcheck disable=SC1087
# O modelo usa $e seguido de texto entre colchetes, não um acesso a um array.
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then
    value="${value:1:${#value}-2}"
    value="${value//"$sq"/\'}"
  fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if ((rc)) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if ((rc)) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : >"$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >>"$tmp"
  cat "$tmp" >"$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"
export PATH="$HOME/.bun/bin:$HOME/.local/bin:$PATH"

# A biblioteca mantém-se intacta. Estas funções adaptam o texto e a interação.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\nEtapa %s de %s: %s\n' "$_STAGE_INDEX" "$TOTAL_STAGES" "$1"
}
run() {
  printf '  A executar: %s\n' "$*"
  "$@"
}
fail() {
  printf '%sErro: %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}
trap 'printf "\nA configuração falhou. Corrija o erro acima e volte a executar este script.\n" >&2' ERR

say "Configuração do Cairn Web para Ubuntu e WSL."
say "Os comandos são automáticos. O sudo pode pedir a sua palavra-passe."
say "Pode interromper com Ctrl+C e voltar a executar o script."

stage "Verificar o sistema e instalar as ferramentas de base"
[[ "$(uname -s)" == Linux && -f /etc/os-release ]] || fail "Este script requer Ubuntu ou Ubuntu em WSL. No Windows, use scripts/setup-project.ps1."
# /etc/os-release é fornecido pelo sistema operativo.
. /etc/os-release
[[ "${ID:-}" == ubuntu ]] || fail "Este script suporta Ubuntu. Sistema detetado: ${ID:-desconhecido}."
case "$(uname -m)" in
x86_64) NODE_ARCH=x64 ;;
aarch64) NODE_ARCH=arm64 ;;
*) fail "Arquitetura não suportada: $(uname -m)." ;;
esac
missing=()
for tool in git curl unzip xz sha256sum tar; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    case "$tool" in
    xz) missing+=(xz-utils) ;;
    sha256sum) missing+=(coreutils) ;;
    *) missing+=("$tool") ;;
    esac
  fi
done
if ((${#missing[@]})); then
  if [[ "$EUID" == 0 ]]; then
    run apt-get update
    run apt-get install -y "${missing[@]}" ca-certificates
  else
    command -v sudo >/dev/null 2>&1 || fail "Peça ao administrador que instale: ${missing[*]} e ca-certificates."
    run sudo apt-get update
    run sudo apt-get install -y "${missing[@]}" ca-certificates
  fi
fi
run git --version

stage "Instalar Bun 1.3.14 e verificar Node.js"
TMP_SETUP=$(mktemp -d)
trap 'rm -rf -- "$TMP_SETUP"' EXIT
if ! command -v bun >/dev/null 2>&1 || [[ "$(bun --version)" != 1.3.14 ]]; then
  say "A descarregar o instalador oficial do Bun."
  run curl --fail --silent --show-error --location https://bun.sh/install --output "$TMP_SETUP/install-bun.sh"
  run env BUN_INSTALL="$HOME/.bun" bash "$TMP_SETUP/install-bun.sh" bun-v1.3.14
fi
[[ "$(bun --version)" == 1.3.14 ]] || fail "Não foi possível ativar o Bun 1.3.14."
node_ready() {
  command -v node >/dev/null 2>&1 && node -e 'const [a,b]=process.versions.node.split(".").map(Number); process.exit(a>22 || (a===22 && b>=12) ? 0 : 1)'
}
if ! node_ready; then
  NODE_VERSION=22.23.2
  archive="node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz"
  base="https://nodejs.org/dist/v$NODE_VERSION"
  run curl --fail --silent --show-error --location "$base/$archive" --output "$TMP_SETUP/$archive"
  run curl --fail --silent --show-error --location "$base/SHASUMS256.txt" --output "$TMP_SETUP/SHASUMS256.txt"
  (
    cd "$TMP_SETUP"
    grep "  $archive$" SHASUMS256.txt | sha256sum --check
  )
  destination="$HOME/.local/share/cairn/node-v$NODE_VERSION-linux-$NODE_ARCH"
  mkdir -p "$HOME/.local/share/cairn" "$HOME/.local/bin"
  run tar -xJf "$TMP_SETUP/$archive" -C "$HOME/.local/share/cairn"
  if [[ -e "$HOME/.local/bin/node" || -L "$HOME/.local/bin/node" ]]; then
    fail "Já existe $HOME/.local/bin/node. Atualize-o para Node.js 22.12 ou superior e repita a configuração. O script não o substitui."
  fi
  ln -s "$destination/bin/node" "$HOME/.local/bin/node"
  hash -r
fi
node_ready || fail "É necessário Node.js 22.12 ou superior."
run node --version
run bun --version

stage "Instalar as dependências do projeto"
run bun install --frozen-lockfile

stage "Preparar Gitleaks e Chromium"
if [[ ! -x .tools/gitleaks ]] || [[ "$(.tools/gitleaks version)" != 8.30.0 ]]; then
  case "$NODE_ARCH" in
    x64) platform=linux_x64; checksum=79a3ab579b53f71efd634f3aaf7e04a0fa0cf206b7ed434638d1547a2470a66e ;;
    arm64) platform=linux_arm64; checksum=b4cbbb6ddf7d1b2a603088cd03a4e3f7ce48ee7fd449b51f7de6ee2906f5fa2f ;;
  esac
  run curl --fail --silent --show-error --location "https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_$platform.tar.gz" --output "$TMP_SETUP/gitleaks.tar.gz"
  printf '%s  %s\n' "$checksum" "$TMP_SETUP/gitleaks.tar.gz" | sha256sum --check
  mkdir -p .tools
  run tar -xzf "$TMP_SETUP/gitleaks.tar.gz" -C .tools gitleaks
  run .tools/gitleaks version
fi
# --with-deps instala também as bibliotecas de sistema de que o Chromium precisa.
run env PLAYWRIGHT_SKIP_BROWSER_GC=1 bunx playwright@1.64.0 install --with-deps chromium

stage "Verificar o projeto"
run bun run check
say "Configuração concluída. As verificações terminaram sem erros."
say "O projeto ainda não tem testes automáticos. Estas verificações não comprovam o comportamento da aplicação."
say "Para iniciar o projeto, abra um terminal nesta pasta e execute:"
printf '  export PATH="$HOME/.bun/bin:$HOME/.local/bin:$PATH"\n  bun run dev\n'
say "Abra o endereço apresentado pelo Vite, normalmente http://localhost:5173."
say "Não é necessário criar um ficheiro .env. Discord, WhatsApp e publicação são configurações separadas."
